use dbmyshop;

INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Smartphone Samsung Galaxy S21', 5000.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Smartphone Apple iPhone 13', 6000.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Smartphone Xiaomi Mi 11', 4000.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Notebook Dell Inspiron', 5000.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Notebook Lenovo IdeaPad', 4500.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Notebook HP Pavilion', 4000.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Tablet Samsung Galaxy Tab S7', 4000.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Tablet Apple iPad Air', 5000.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Smartwatch Samsung Galaxy Watch4', 2000.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Smartwatch Apple Watch Series 7', 3000.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Fone de ouvido sem fio Samsung Galaxy Buds2', 800.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Fone de ouvido sem fio Apple AirPods Pro', 1200.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Monitor Dell UltraSharp', 2000.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Monitor LG UltraGear', 2500.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Teclado mecânico HyperX Alloy FPS Pro', 500.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Mouse gamer Logitech G502 HERO', 300.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Headset gamer HyperX Cloud II', 600.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Placa de vídeo NVIDIA GeForce RTX 3080', 10000.0, 50);
INSERT INTO produto(nome_produto, preco_produto, qtdeEstoque_produto) VALUES('Processador AMD Ryzen 9 5900X', 4000.0, 50);